[package]
name = "insides"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dilate = { git = "https://github.com/alexmadeathing/dilate.git" }

[dev-dependencies]
serde = { version = "1.0.136", features = ["derive"] } # For test data serialisation
serde_json = "1.0.78" # For test data serialisation
lazy_static = "1.4.0" # For test data
paste = "1.0.6" # For generation of multi-dimensional, multi-type, test names
